subfolders:
- 770-network-addon-mod/1-core
- 770-network-addon-mod/2-networks
- 770-network-addon-mod/3-overrides
- 770-network-addon-mod/6-misc
- 770-network-addon-mod/8-textures
- 770-network-addon-mod/9-patches

extra-channels: []

allow-ego-perspective: false

lowercase-file-names: true

# Package names for which the check for asset version mismatches should be skipped.
# Only needed when the linter tells you so.
ignore-version-mismatches:
- vortext:vortexture-1
- vortext:vortexture-2
- t-wrecks:industrial-revolution-mod-addon-set-i-d
- memo:industrial-revolution-mod
- bsc:mega-props-jrj-vol01
- bsc:mega-props-diggis-canals-streams-and-ponds
- bsc:mega-props-rubik3-vol01-wtc-props
- bsc:mega-props-newmaninc-rivers-and-ponds
- nam:controller

group-to-github:
- null-45: "0xC0000054"
- simmaster07: nsgomez
- memo: memo33
- nam: NAMTeam

# The following is only appropriate when nobody can make unnoticed changes to
# the metadata checksum fields.
ignore-non-github-urls:
- simmaster07-extra-cheats-dll
- buggi-extra-cheats-dll
- simmaster07-real-upgradeable-city-halls

single-choice-variants:
- invisichem:colossus-addon-mod-legacy:patch-method

# Package identifiers for which the check against identifiers of the form `group:group-name` is skipped. Usually, prefer `group:name` instead.
ignore-group-prefixes-in-name:
- bsc:bsc-parks-texture-pack
- vip:vip-terrain-mod-base
- vip:vip-terrain-mod-beach
- vip:vip-terrain-mod-complete
- vip:vip-terrain-mod-rock
- vip:vip-terrain-mod-water

ignore-nonunique-includes:
- invisichem:colossus-addon-mod-legacy
- philforhockey51:bocage
- nam:controller
